# Generated by Django 3.1.6 on 2021-02-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clients',
            unique_together={('name', 'phone')},
        ),
    ]
