# Generated by Django 3.1.6 on 2021-02-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productcategories_products_producttypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
